num_workers: &num_workers 4

NAIVE_STAGE:
  init:
    loader:
      module: iteration
      args:
        batch_size: 1
        iterations: 150 # 0~150k
        num_workers: *num_workers
    dataset_state:
      scale: 8
    model_state: {}
  tree:
    loader:
      module: iteration
      args:
        batch_size: 1
        iterations: 550
        num_workers: *num_workers
    dataset_state:
      scale: 1 # 4
    render_state:
      render_depth: False
    model_state:
      enable_sh: True