parents:
  - config/example/test_full_resol/dataset.yml
  - config/example/test_full_resol/level_of_gaussian.yml
  - config/example/test_full_resol/stage_8_4.yml

#exp: output/example/test/log
#exp: output/example/test_zoomgs_01/log
exp: output/example/test_zoomgs_01_full_resol/log
gpus: [0]

log_interval: 1000
save_interval: 10_000

max_steps: 750

RGB_RENDER_L1_SSIM:
  module: LoG.render.renderer.NaiveRendererAndLoss
  args:
    use_origin_render: False
    use_randback: True

train:
  dataset: $dataset
  render: $RGB_RENDER_L1_SSIM
  stages: $NAIVE_STAGE
  init:
    method: scale_min
    dataset_state:
      scale: 1 # 4

val:
  dataset: $val_dataset
  iteration: 10000