parents:
  - config/example/test/dataset.yml
  - config/example/test/level_of_gaussian.yml
  - config/example/test/stage_8_4.yml

#exp: output/example/test/log_wdepth
exp: output/example/test_zoomgs_01/log_wdepth
gpus: [0]

log_interval: 1000
save_interval: 10_000

max_steps: 750

dataset:
  module: LoG.dataset.colmap.DepthDataset
  args:
    depth_scale: 8

RGB_RENDER_L1_SSIM:
  module: LoG.render.renderer.NaiveRendererAndLoss
  args:
    use_origin_render: False
    use_randback: True
    render_depth: True

train:
  dataset: $dataset
  render: $RGB_RENDER_L1_SSIM
  stages: $NAIVE_STAGE
  init:
    method: scale_min
    dataset_state:
      scale: 4

val:
  dataset: $val_dataset
  iteration: 10000